<?php
define( 'WPSHARE247_AEIWOOC_PLUGIN_EXCEL_LIB_DIR', WPSHARE247_AEIWOOC_PLUGIN_INC_DIR . '/excel-lib' );
define( 'WPSHARE247_AEIWOOC_PLUGIN_PRO_DIR', WPSHARE247_AEIWOOC_PLUGIN_EXCEL_LIB_DIR . '/excel.pro' );
define( 'WPSHARE247_AEIWOOC_PLUGIN_PRO_TEMPLATES_DIR', WPSHARE247_AEIWOOC_PLUGIN_PRO_DIR . '/templates' );
define( 'WPSHARE247_AEIWOOC_PLUGIN_DEMO_DIR', WPSHARE247_AEIWOOC_PLUGIN_EXCEL_LIB_DIR . '/demo' );
define( 'WPSHARE247_AEIWOOC_PLUGIN_INC_ASSETS', WPSHARE247_AEIWOOC_PLUGIN_DIR . '/assets' );
define( 'WPSHARE247_AEIWOOC_PLUGIN_INC_ASSETS_URL', plugins_url('assets', WPSHARE247_AEIWOOC ) );
define( 'WPSHARE247_AEIWOOC_PLUGIN_PRO_TEMPLATES_URL', plugins_url('inc/excel-lib/excel.pro/templates', WPSHARE247_AEIWOOC )  );
define( 'WPSHARE247_AEIWOOC_PLUGIN_DEMO_TEMPLATES_URL', plugins_url('inc/excel-lib/demo', WPSHARE247_AEIWOOC )  );

define( 'WPSHARE247_AEIWOOC_TEXTDOMAIN', 'wpshare247-attach-excel-invoice-wooc' );
define( 'WPSHARE247_AEIWOOC_SETTING_PAGE_SLUG', 'Aeiwooc-options' );
define( 'WPSHARE247_AEIWOOC_PREFIX', 'Aeiwooc_' );
define( 'WPSHARE247_AEIWOOC_FILE_PATH', 'wpshare247_aeiwooc_woocommerce_invoices' );